[Feature] #13 Create EditorContents Entity, Model, UseCase
DeveloperAcademy-POSTECH/MC2-Team2-GreedySquirrel pull request #15
Opened 2022-06-12 05:20 UTC by Gobans

# Issue Number
🔒 Close #13 

## Changes

- Changed files
campair/campair.xcodeproj/project.pbxproj
campair/campair/Entity/EditorCollection.swift
campair/campair/Entity/EditorCollectionData.json
campair/campair/Entity/EditorContent .swift
campair/campair/Entity/EntityPlaceHolder.swift
campair/campair/Entity/Equipment.swift
campair/campair/Model/EditorRepository.swift
campair/campair/Model/ModelPlaceHolder.swift
campair/campair/UseCase/EditorUseCase.swift
campair/campair/UseCase/UseCasePlaceHolder.swift
campair/campair/ViewModel/EditorViewModel.swift
campair/campair/ViewModel/ViewModelPlaceHolder.swift

## New features

- Create the EditorContents Entity

## Review points

- I create the EditorCollection to arrange EditorContents, Equipment is also need for EditorContents.
- Make EditorRepository for fetch EditorCollection with EditorUseCase

## Questions

- Is there any ambiguity of Function name or Struct name?

## Checklist

- [x] Is the branch you are merging on correct?
- [x] Do you comply with coding conventions?
- [x] Are there any changes not related to PR?
- [x] Has my code been self-reviewed?

2022-06-12 08:35 UTC, rriver2 requested changes

2022-06-12 08:35 UTC, rriver2 commented on campair/campair/ViewModel/EditorViewModel.swift
> +            self.titleText = editorCollection.editorContents[0].title
There may not be a zero index, so I think you need a code to process the nil.

2022-06-12 08:35 UTC, rriver2 commented on campair/campair/Model/EditorRepository.swift
> +    case stringifyError
It's stated that it's an error, but I think it's a bad idea to add another error after the error name. I wanted to find the error naming data and upload it, but I couldn't find any data to refer to. 
Let's think about it together.

https://www.swift.org/documentation/api-design-guidelines/#naming
-> reference "Omit needless words" part
(This is how to name and annotate the variable/function/parameter/forwarding factor labels, but I think it might similar to error naming too.)

2022-06-12 08:35 UTC, rriver2 commented on campair/campair/Entity/Equipment.swift
> +struct Equipment: Codable {
I interpreted "장비" as tool and decided the name of the view, should I change it to Equipment? And I think it would be good to decide on some other terms on Monday.

2022-06-12 11:53 UTC, sustainable-git commented on campair/campair/Entity/Equipment.swift
> +struct Equipment: Codable {
GGOODD!

2022-06-12 11:53 UTC, sustainable-git commented on campair/campair/Model/EditorRepository.swift
> +    case stringifyError
GGOODD

2022-06-12 11:59 UTC, sustainable-git requested changes
Go goban!

2022-06-12 11:59 UTC, sustainable-git commented on campair/campair/Entity/Equipment.swift
> +    let description: String
System sometimes use description. Please change the name

2022-06-12 11:59 UTC, sustainable-git commented on campair/campair/ViewModel/EditorViewModel.swift
> +        editorUseCase.getEditorCollection { editorCollection in
You should explicitly add `self.` in front of UseCase

2022-06-12 11:59 UTC, sustainable-git commented on campair/campair/ViewModel/EditorViewModel.swift
> +    let editorUseCase = EditorUseCase(repository: EditorRepository())
If there is only one UseCase in ViewModel, you just need to state UseCase, not EditorUseCase

2022-06-12 11:59 UTC, sustainable-git commented on campair/campair/ViewModel/EditorViewModel.swift
> +        editorUseCase.getEditorCollection { editorCollection in
ViewModel is a class so that you should consider circular reference here.
Notate [weak self] in closure.

2022-06-13 02:51 UTC, Gobans commented on campair/campair/ViewModel/EditorViewModel.swift
> +            self.titleText = editorCollection.editorContents[0].title
This is testing code, later I will add some code to process the nil. Thank you!

2022-06-13 03:01 UTC, unnnyong commented on campair/campair/Model/EditorRepository.swift
> +struct EditorRepository: EditorcontentsFetchable {
struct 에서 구현된 method 의 parameter 의 completionHandler 대신, Swift의 async await를 사용하면 indent도 줄어들고 사용하는 쪽에서도, 깔끔해질 수 있을 것 같아요 ~

2022-06-13 03:02 UTC, unnnyong commented on campair/campair/UseCase/EditorUseCase.swift
> +    let repository: EditorcontentsFetchable
```suggestion
    private let repository: EditorcontentsFetchable
```

struct 내에서만 필요한 정수는 접근제한자 설정이 좋을 것 같아용

2022-06-13 03:02 UTC, unnnyong commented on campair/campair/ViewModel/EditorViewModel.swift
> +class EditorViewModel: ObservableObject {
```suggestion
final class EditorViewModel: ObservableObject {
```

2022-06-13 03:03 UTC, unnnyong commented on campair/campair/ViewModel/EditorViewModel.swift
> +import Foundation
```suggestion
import Combine
import Foundation
```

사용되는 모듈을 한 눈에 보여주면 읽는쪽에서 어느 프레임워크를 사용해서 구현하는구나 라고 한눈에 알아보기 쉬워집니다
ObservableObject가 사용되는 것 같으니 콤바인도 추가합시다요 ~~~~

2022-06-13 03:09 UTC, rriver2 commented on campair/campair/ViewModel/EditorViewModel.swift
> +            self.titleText = editorCollection.editorContents[0].title
Okay, I got it !

2022-06-13 03:09 UTC, Gobans commented on campair/campair/Entity/Equipment.swift
> +struct Equipment: Codable {
Decided to use Equipment! 🌈

2022-06-13 04:01 UTC, rriver2 commented on campair/campair/Entity/Equipment.swift
> +    let description: String
에디터 메인화면
var editorContents : [EditorContent]

struct EditorContent {
	let opening : OpeningSection
	let equipmentContents : [EquipmentContent]
}

struct OpeningSection {
	let cardPaintingURL : URL
	let cardTitle : String
	let cardSubTitle : String
	let Title : String
	let SubTitle : String
}

struct EquipmentContent {
	let title : String
	let upperContent : String
	let recommendedEquipments : [Equipment]
	let lowerContent : String
}

struct Equipment {
	let paintingURL : URL
	let title : String
	let content : String
	let props : String
	let cons : String
}

2022-06-13 04:54 UTC, sustainable-git commented on campair/campair/UseCase/EditorUseCase.swift
> +    let repository: EditorcontentsFetchable
@unnnyong 감사합니다! 중요한 부분이죠.

2022-06-13 04:55 UTC, sustainable-git commented on campair/campair/ViewModel/EditorViewModel.swift
> +class EditorViewModel: ObservableObject {
@unnnyong 감사합니다! 성능!

2022-06-13 04:57 UTC, sustainable-git requested changes

2022-06-13 04:57 UTC, sustainable-git commented on campair/campair/ViewModel/EditorViewModel.swift
> +//  ViewModelPlaceHolder.swift
Please change this comment

2022-06-13 04:57 UTC, sustainable-git commented on campair/campair/ViewModel/EditorViewModel.swift
> +import Foundation
ViewModel should import `SwiftUI` instead of `Foundation`.

2022-06-13 06:13 UTC, rriver2 commented on campair/campair/Entity/Equipment.swift
> +    let description: String
## This is an example of jsonfile
{
    "editorContent" : {
        "opening": {
            "cardPaintingURL" : "주소",
            "cardTitle" : "차로 떠나는 피크닉",
            "cardSubTitle" : "초보차크닉",
            "Title" : "최소한으로 차크닉을 떠날 때.",
            "SubTitle" : "떠나는 여행이 돌아왔어요. 간단한 장비들로 시작할 수 있는 차로 떠나는 피크닉, 차크닉을 떠나보세요!"
        },
        "equipmentContents" : [
            {
                "title" : "경량 의자"
                "upperContent" : "산에서도 바다에서도 의자만 있다면 그곳이 여러분의 차크닉 장소예요. 드넓은 초원과 끝없이 이어지는 바다를 바라보는 것에서 차크닉의 힐링이 시작돼요. 앉아서 즐기는 모든 것들을 경량 의자와 함께하세요."
                "recommendedEquipments" : [
                    {
                        "paintingURL" : "주소",
                        "title" : "경량 의자",
                        "content" : "릴렉스 체어는 엉덩이부터 목 바로 아래까지 몸 전체를 감싸 주는 형태의 의자예요. 앉으면 하늘을 보며 반쯤 누워있는 편한 자세를 취할 수 있어요. 경량 의자보다는 부피가 크지만 더 넓은 범위를 감싸 주기 때문에 쉴 수 있어요!",
                        "props" : [
                            "의자에서 누워있는 듯한 느낌이에요. '쉼'을 목적으로 나온 의자.",
                            "다리 폭이 넓어서 넘어질 위험이 적어요."
                        ],
                        "cons" : [
                            "접었을 때도 사이즈가 크고 무거워요.",
                            "앉아서 음식을 먹거나 책을 읽을 때는 불편할 수 있어요."
                        ]
                    }
                ]
                "lowerContent" : "평범한 자동차 여행에서 작지만 확실한 행복을 경량 의자에서 느낄 수 있어요. 혼자 또 같이 소소한 힐링을 느껴보세요. 용도에 따라 취향에 따라 부피에 따라 다양한 의자를 사용해보세요. 처음에는 등받이가 있는 캠핑용 경량 의자를 추천해요. 의자에 앉아서 행복한 차크닉을 즐겨보세요."
            },
            {
                "title" : "돗자리"
                "upperContent" : "돗자리 upperContent"
                "recommendedEquipments" : [
                    {
                        "paintingURL" : "주소",
                        "title" : "돗자리",
                        "content" : "돗자리 상세 content",
                        "props" : [
                            "돗자리 장점 1",
                            "돗자리 장점 2"
                        ],
                        "cons" : [
                            "돗자리 단점 1",
                            "돗자리 단점 2"
                        ]
                    }
                ]
                "lowerContent" : "돗자리 lowerContent"
            },
            {
                "title" : "이런 장비도 있으면 좋아요."
                "upperContent" : "그늘이 없는 곳으로 차크닉을 떠나면 햇빛의 공격을 받을 수 있어요. 햇빛을 가릴 수 있는 어닝이나 타프 혹은 그늘막텐트를 구비하면 오랜 시간 차크닉을 즐길 수 있을 거에요."
                "recommendedEquipments" : [
                    {
                        "paintingURL" : "주소",
                        "title" : "어닝/사이드월",
                        "content" : "어닝/사이드월 상세 content",
                        "props" : [
                            "어닝/사이드월 장점 1",
                            "어닝/사이드월 장점 2"
                        ],
                        "cons" : [
                            "어닝/사이드월 단점 1",
                            "어닝/사이드월 단점 2"
                        ]
                    },
                    {
                        "paintingURL" : "주소",
                        "title" : "렉타 타프",
                        "content" : "렉타 타프 상세 content",
                        "props" : [
                            "렉타 타프 장점 1",
                            "렉타 타프 장점 2"
                        ],
                        "cons" : [
                            "렉타 타프 단점 1",
                            "렉타 타프 단점 2"
                        ]
                    }
                ]
                "lowerContent" : "차크닉, 차박, 캠핑에 필요한 장비 다 볼 수 있어요. 더 많은 장비를 만나보고 싶다면, 장비 사전 탭을 방문하세요."
            }
        ]
    }
}

2022-06-13 06:45 UTC, Gobans commented on campair/campair/ViewModel/EditorViewModel.swift
> +    let editorUseCase = EditorUseCase(repository: EditorRepository())
okay~ But just in case use one more use case, I suspend refactoring.

2022-06-13 06:50 UTC, Gobans commented on campair/campair/UseCase/EditorUseCase.swift
> +    let repository: EditorcontentsFetchable
Thanks! yong!

2022-06-13 06:51 UTC, Gobans commented on campair/campair/ViewModel/EditorViewModel.swift
> +class EditorViewModel: ObservableObject {
okay~! 땡스용 ~

2022-06-13 06:56 UTC, Gobans commented on campair/campair/ViewModel/EditorViewModel.swift
> +import Foundation
> ViewModel should import `SwiftUI` instead of `Foundation`.

@sustainable-git Young maybe said we should clarify framework what we used for. So I followed her comment.

2022-06-13 06:58 UTC, Gobans commented on campair/campair/ViewModel/EditorViewModel.swift
> +//  ViewModelPlaceHolder.swift
okay I fixed it, thank you

2022-06-13 07:53 UTC, Gobans commented on campair/campair/Model/EditorRepository.swift
> +struct EditorRepository: EditorcontentsFetchable {
Because of out of time, I will refactoring later. Thank you!

2022-06-13 07:54 UTC, sustainable-git approved these changes

2022-06-13 08:09 UTC, unnnyong commented on campair/campair/Model/EditorRepository.swift
> +struct EditorRepository: EditorcontentsFetchable {
When is the **later**... ? 🤩

2022-06-13 08:26 UTC, merged