[Feature] #16, #17 : Add ToolDictionaryMainView UI
DeveloperAcademy-POSTECH/MC2-Team2-GreedySquirrel pull request #18
Opened 2022-06-12 06:21 UTC by rriver2

# Issue Number
🔒 Close #16 
🔒 Close #17 

## Changes

- Changed files
    - campair/campair.xcodeproj/project.pbxproj
    - campair/campair/View/ToolDictionary/ToolDictionaryMainView.swift

## New features

- Create the ToolDictionaryMainView's SearchBar UI 
- Create the ToolDictionaryMainView's GridView UI 

## Checklist

- [x] Is the branch you are merging on correct?
- [ ] Do you comply with coding conventions?
- [x] Are there any changes not related to PR?
- [x] Has my code been self-reviewed?

2022-06-12 06:22 UTC, sustainable-git commented on campair/campair/View/ToolDictionary/ToolDictionaryMainView.swift
> +let columns: [GridItem] = [
You should not declare global property here...
Use nested style instead

2022-06-12 06:23 UTC, sustainable-git commented on campair/campair/View/ToolDictionary/ToolDictionaryMainView.swift
> +                    .font(.system(size:25))
Font size should not be fixed.
Please consider accessibility.

2022-06-12 06:29 UTC, sustainable-git requested changes
Please check review :)

2022-06-12 06:29 UTC, sustainable-git commented on campair/campair/View/ToolDictionary/ToolDictionaryMainView.swift
> +                            TextField("검색어를 입력하세요.", text: $searchWord)
Our coding convention has a rule about using explicit self
Please use `self.` in front of `$searchWord`

2022-06-12 06:45 UTC, rriver2 commented on campair/campair/View/ToolDictionary/ToolDictionaryMainView.swift
> +                            TextField("검색어를 입력하세요.", text: $searchWord)
thank you. I fixed it

2022-06-12 06:45 UTC, rriver2 commented on campair/campair/View/ToolDictionary/ToolDictionaryMainView.swift
> +let columns: [GridItem] = [
thank you.  I fixed it

2022-06-12 06:47 UTC, rriver2 commented on campair/campair/View/ToolDictionary/ToolDictionaryMainView.swift
> +                    .font(.system(size:25))
Thank you. But I want to ask berry's opinion. After her hi-fi drawing, I will reflect this.  @vveryberry

2022-06-13 03:05 UTC, unnnyong commented on campair/campair/View/ToolDictionary/ToolDictionaryMainView.swift
> +    @State private var searchWord : String = ""
```suggestion
    @State private var searchWord = ""
```

Int, Double, Float 가 아닌경우에는 Swift의 타입 속도을 믿고 생략해도 좋을 것 같아요 ~

2022-06-13 03:06 UTC, unnnyong commented on campair/campair/View/ToolDictionary/ToolDictionaryMainView.swift
> +                    .font(.system(size:25))
```suggestion
                    .font(.system(size: 25))
```

보통의 Swift 코드 스타일로는 Colon 뒤에 스페이스 하나가 추천됩니다 ~

2022-06-13 03:07 UTC, unnnyong commented on campair/campair/View/ToolDictionary/ToolDictionaryMainView.swift
> +            .navigationTitle("")
Title이 나중에 추가되나요 ? 아니면 이유가 있어서 `""`가 들어간것인가용 ?

2022-06-13 03:07 UTC, unnnyong commented on campair/campair/View/ToolDictionary/ToolDictionaryMainView.swift
> +    let name : String
이곳에서만 사용된다면 private 설정이 좋을 것 같아요 ~
```suggestion
    private let image : Image
    private let name : String
```

2022-06-13 03:08 UTC, unnnyong commented on campair/campair/View/ToolDictionary/ToolDictionaryMainView.swift
> +
추후에 액션이 추가된다면 TODO로 잊지않을 수 있어요 ~ !
```suggestion
            // TODO: Add Handling
```

2022-06-13 03:11 UTC, unnnyong commented on campair/campair/View/ToolDictionary/ToolDictionaryMainView.swift
> +                                .padding(.horizontal, 10)
사용되는 아이콘? SFSymbol들을 어디에서 관리하면 어때요 ?

```swift
enum Symbol: String {
    case search = "magnifyingglass"
}
```

2022-06-13 03:12 UTC, unnnyong commented
diff 양도, PR 본문도 심플해서 리뷰하기 너무 편했어요 ~~~~~~~ ! 감사합니다 ❤️

2022-06-13 07:03 UTC, rriver2 commented on campair/campair/View/ToolDictionary/ToolDictionaryMainView.swift
> +                    .font(.system(size:25))
I fixed it thank you !

2022-06-13 07:05 UTC, rriver2 commented on campair/campair/View/ToolDictionary/ToolDictionaryMainView.swift
> +            .navigationTitle("")
Oh, I did't delete this code. Thank you for finding this. I fixed it ~ !

2022-06-13 07:07 UTC, rriver2 commented on campair/campair/View/ToolDictionary/ToolDictionaryMainView.swift
> +    let name : String
I think this part will be modified to move on to the next view after the entity is decided.

2022-06-13 07:10 UTC, rriver2 commented on campair/campair/View/ToolDictionary/ToolDictionaryMainView.swift
> +
Good ~~! Thank you for letting me know!

2022-06-13 07:12 UTC, rriver2 commented on campair/campair/View/ToolDictionary/ToolDictionaryMainView.swift
> +    @State private var searchWord : String = ""
> PR 본문

Thank you young !

2022-06-13 07:27 UTC, rriver2 commented on campair/campair/View/ToolDictionary/ToolDictionaryMainView.swift
> +    @State private var searchWord : String = ""
didn't know this! Thank you for explan this ~ Thank you yong ><

2022-06-13 07:41 UTC, unnnyong approved these changes
🚀 🚀 🚀 🚀

2022-06-13 08:38 UTC, merged