[Feature] #19, #20 : Add ToolDictionaryDetailView UI
DeveloperAcademy-POSTECH/MC2-Team2-GreedySquirrel pull request #22
Opened 2022-06-12 08:12 UTC by rriver2

# Issue Number
🔒 Close #19 
🔒 Close #20 

## Changes

- Changed files
    - campair/campair/View/ToolDictionaryDetailView.swift

## New features

- Create the ToolDictionaryDetailView's SearchBar UI (ScrollView , show detail tools)

## Review points

- I don't know if I split the view in a good way.

## Checklist

- [x] Is the branch you are merging on correct?
- [x] Do you comply with coding conventions?
- [x] Are there any changes not related to PR?
- [x] Has my code been self-reviewed?

2022-06-12 10:37 UTC, sustainable-git requested changes
There is no SearchBar UI...

2022-06-13 05:04 UTC, sustainable-git commented on campair/campair/View/ToolDictionaryDetailView.swift
> +
use `// todo` here

2022-06-13 05:04 UTC, sustainable-git commented on campair/campair/View/ToolDictionaryDetailView.swift
> +                HStack( spacing: 30){
```suggestion
                HStack(spacing: 30) {
```
check indent! :)

2022-06-13 05:04 UTC, sustainable-git commented on campair/campair/View/ToolDictionaryDetailView.swift
> +                        Button(action: {
```suggestion
                        Button {
                            self.selectedToolNumber = index
                        } label: {
```
Keep closure expressions simple :)

2022-06-13 09:14 UTC, rriver2 commented on campair/campair/View/ToolDictionaryDetailView.swift
> +
Good !

2022-06-13 09:18 UTC, rriver2 commented on campair/campair/View/ToolDictionaryDetailView.swift
> +                HStack( spacing: 30){
good

2022-06-13 09:19 UTC, rriver2 commented on campair/campair/View/ToolDictionaryDetailView.swift
> +                        Button(action: {
thank you ~

2022-06-13 10:52 UTC, merged